BASE_URL_OLD = "https://api.city-mind.com"
BASE_URL_NEW = "https://api-ctm.city-mind.com"

CONSUMER_URL_OLD = f"{BASE_URL_OLD}/consumer"
CONSUMER_URL_NEW = f"{BASE_URL_NEW}/consumer"

CONSUMPTION_URL = f"{BASE_URL_NEW}/consumption"

API_HEADER_TOKEN = "x-access-token"

API_URL_OLD = "https://api.city-mind.com"
API_URL_NEW = "https://api-ctm.city-mind.com"

CITY_MIND_WEBSITE = "https://rym-pro.com"

ENDPOINT_PARAMETER_METER_ID = "meter_id"
ENDPOINT_PARAMETER_YESTERDAY = "yesterday"
ENDPOINT_PARAMETER_TODAY = "today"
ENDPOINT_PARAMETER_LAST_DAY_MONTH = "last_day_month"
ENDPOINT_PARAMETER_MUNICIPALITY_ID = "municipality_id"
ENDPOINT_PARAMETER_CURRENT_MONTH = "current_month"
ENDPOINT_PARAMETER_ALERT_TYPE = "alert_type"

ENDPOINT_CONSUMER_OLD = f"{API_URL_OLD}/consumer"
ENDPOINT_CONSUMER_NEW = f"{API_URL_NEW}/consumer"

ENDPOINT_CONSUMPTION_NEW = f"{API_URL_NEW}/consumption"

ENDPOINT_MUNICIPALS_OLD = f"{API_URL_OLD}/municipals"
ENDPOINT_MUNICIPALS_NEW = f"{API_URL_NEW}/municipality"

ENDPOINT_LOGIN = f"{ENDPOINT_CONSUMER_OLD}/login"

ENDPOINT_ME = f"{ENDPOINT_CONSUMER_OLD}/me"
ENDPOINT_METERS = f"{ENDPOINT_CONSUMER_NEW}/meters"
ENDPOINT_UNITS = f"{ENDPOINT_MUNICIPALS_OLD}/h1/measurmentunits"
ENDPOINT_CUSTOMER_SERVICE = f"{ENDPOINT_MUNICIPALS_OLD}/municipalCustomerService"

ENDPOINT_ALERTS_FOR_SETTINGS = f"{ENDPOINT_CONSUMER_NEW}/alertsForSettings"

ENDPOINT_LAST_READ = f"{ENDPOINT_CONSUMPTION_NEW}/last-read"
ENDPOINT_CONSUMPTION_DAILY = f"{ENDPOINT_CONSUMPTION_NEW}/daily/lastbillingCycle/{{meter_id}}/{{yesterday}}/{{today}}"
ENDPOINT_CONSUMPTION_MONTHLY = f"{ENDPOINT_CONSUMPTION_NEW}/monthly/{{meter_id}}/{{current_month}}/{{last_day_month}}"
ENDPOINT_VACATIONS = f"{ENDPOINT_CONSUMER_OLD}/vacations"
ENDPOINT_MY_ALERTS = f"{ENDPOINT_CONSUMER_NEW}/myalerts"
ENDPOINT_MY_ALERTS_SETTINGS = f"{ENDPOINT_CONSUMER_OLD}/myalerts/settings"
ENDPOINT_MY_MESSAGES = f"{ENDPOINT_MUNICIPALS_NEW}/{{municipality_id}}/messages"
ENDPOINT_MY_MESSAGE_SUBJECTS = f"{ENDPOINT_MY_MESSAGES}/message-subjects"
ENDPOINT_CONSUMPTION_LOW_RATE_LIMIT = f"{ENDPOINT_CONSUMPTION_NEW}/Low-Rate-Limit"
ENDPOINT_CONSUMPTION_FORECAST = f"{ENDPOINT_CONSUMPTION_NEW}/forecast/{{meter_id}}"
ENDPOINT_MY_ALERTS_SETTINGS_UPDATE = f"{ENDPOINT_MY_ALERTS}/settings/{{alert_type}}"

API_DATA_TOKEN = "token"
API_DATA_ERROR_CODE = "code"
API_DATA_ERROR_REASON = "error"

API_DATA_SECTION_ME = "me"
API_DATA_SECTION_METERS = "meters"
# API_DATA_SECTION_UNITS = "units"
API_DATA_SECTION_CUSTOMER_SERVICE = "customer-service"
# API_DATA_SECTION_MY_MESSAGE_SUBJECTS = "my-message-subjects"
# API_DATA_SECTION_ALERTS_FOR_SETTINGS = "alerts-for-settings"
API_DATA_SECTION_LAST_READ = "last-read"
# API_DATA_SECTION_CONSUMPTION_LOW_RATE_LIMIT = "consumption-low-rate-limit"
API_DATA_SECTION_VACATIONS = "vacations"
API_DATA_SECTION_MY_ALERTS = "my-alerts"
API_DATA_SECTION_MY_MESSAGES = "my-messages"
API_DATA_SECTION_CONSUMPTION_DAILY = "consumption-daily"
API_DATA_SECTION_CONSUMPTION_MONTHLY = "consumption-monthly"
API_DATA_SECTION_CONSUMPTION_FORECAST = "consumption-forecast"
API_DATA_SECTION_SETTINGS = "settings"

CUSTOMER_SERVICE_PHONE_NUMBER = "phoneNumber"
CUSTOMER_SERVICE_DESCRIPTION = "description"
CUSTOMER_SERVICE_PHONE_MUNICIPAL_ID = "municipalID"
CUSTOMER_SERVICE_EMAIL = "Email"

METER_COUNT = "meterCount"
METER_SERIAL_NUMBER = "meterSn"
METER_FULL_ADDRESS = "fullAddress"

LAST_READ_METER_COUNT = METER_COUNT
LAST_READ_METER_ID = "meterId"
LAST_READ_VALUE = "read"

ME_FIRST_NAME = "firstName"
ME_LAST_NAME = "lastName"
ME_ACCOUNT_NUMBER = "accountNumber"
ME_PHONE_NUMBER_SECTION = "phoneNumber"
ME_COUNTRY_CODE = "countryCode"
ME_PHONE_NUMBER = "phoneNumber"
ME_ADDITIONAL_PHONE_NUMBER = "AdditionalPhoneNumber"
ME_MUNICIPAL_ID = "municipalId"

CONSUMPTION_METER_COUNT = METER_COUNT
CONSUMPTION_VALUE = "cons"
CONSUMPTION_DATE = "consDate"
CONSUMPTION_ESTIMATION_TYPE = "estimationType"
CONSUMPTION_METER_STATUS_DESC = "meterStatusDesc"
CONSUMPTION_COMMON_DATA = "commonCons"

CONSUMPTION_FORECAST_ESTIMATED_CONSUMPTION = "estimatedConsumption"

SETTINGS_ALERT_TYPE_ID = "alertTypeId"
SETTINGS_MEDIA_TYPE_ID = "mediaTypeId"

ENDPOINT_DATA_INITIALIZE = {
    API_DATA_SECTION_ME: ENDPOINT_ME,
    API_DATA_SECTION_METERS: ENDPOINT_METERS,
    API_DATA_SECTION_CUSTOMER_SERVICE: ENDPOINT_CUSTOMER_SERVICE,
}

ENDPOINT_DATA_UPDATE = {
    # API_DATA_SECTION_VACATIONS: ENDPOINT_VACATIONS,
    # API_DATA_SECTION_MY_ALERTS: ENDPOINT_MY_ALERTS,
    # API_DATA_SECTION_MY_MESSAGES: ENDPOINT_MY_MESSAGES,
    API_DATA_SECTION_SETTINGS: ENDPOINT_MY_ALERTS_SETTINGS
}

ENDPOINT_DATA_UPDATE_PER_METER = {
    API_DATA_SECTION_LAST_READ: ENDPOINT_LAST_READ,
    API_DATA_SECTION_CONSUMPTION_DAILY: ENDPOINT_CONSUMPTION_DAILY,
    API_DATA_SECTION_CONSUMPTION_MONTHLY: ENDPOINT_CONSUMPTION_MONTHLY,
    API_DATA_SECTION_CONSUMPTION_FORECAST: ENDPOINT_CONSUMPTION_FORECAST,
}

ENDPOINT_DATA_RELOAD = {API_DATA_SECTION_SETTINGS: ENDPOINT_MY_ALERTS_SETTINGS}


LOGIN_EMAIL = "email"
LOGIN_PASSWORD = "pw"
LOGIN_DEVICE_ID = "deviceId"

DEFAULT_DEVICE_ID = "test"

FORMAT_DATE_ISO = "%Y-%m-%d"
FORMAT_DATE_YEAR_MONTH = "%Y-%m"
